gem 'jekyll-titles-from-headings'

# --- Required options --- #

# Name of website
title: The Alphanumerics Lab

# Your name to show in the footer
author: Reza Sameni

# --- List of links in the navigation bar --- #
#navbar-links:
header_pages:
  - README.md
  - PROJECTS.md
  - TEAM.md
  - JOBS.md

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/EmoryUniversityDBMI.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: false

theme: minima

plugins:
  jekyll-titles-from-headings
  
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
